/**
 * 관리자 화면 문자열.
 *
 * CRITICAL: 사이트의 `src/config/i18n.ts`를 거치지 않는다. 관리자 전용 키가 사이트 UI
 * 사전에 섞이면 ko/en 두 언어 모두에 불필요한 번역 부담이 생기고, `UIStrings` 키 파리티
 * 검사가 관리자 문구까지 감시하게 된다.
 *
 * 관리자 화면은 한국어 고정이다 — 운영자 1인, 한국어 사용자.
 */

export const L = {
  app: {
    title: '관리자 콘솔',
    devOnly: 'dev 전용',
    openSite: '사이트 열기',
    branch: '브랜치',
    remoteWarning:
      '원격 접근이 허용되어 있습니다. 같은 네트워크의 누구나 이 리포지토리를 수정할 수 있습니다.',
    offline: '개발 서버와 연결이 끊어졌습니다. 다시 연결되면 이 배너가 사라집니다.',
    loading: '불러오는 중…',
  },

  nav: {
    dashboard: '대시보드',
    posts: '글',
    editor: '글 편집기',
    profile: '프로필',
    settings: '설정',
    strings: 'UI 문자열',
    tags: '태그',
    assets: '이미지',
  },

  save: {
    changes: (n: number) => `변경 ${n}건`,
    save: '저장',
    saving: '저장 중…',
    revert: '되돌리기',
    saved: '저장했습니다',
    unsaved: '저장하지 않은 변경이 있습니다. 이 페이지를 떠나시겠습니까?',
    shortcut: 'Ctrl/Cmd+S',
  },

  dashboard: {
    totalPosts: '전체 글',
    totalPostsHint: (published: number, all: number) => `공개 ${published} / 전체 ${all}`,
    drafts: '초안',
    missingTranslation: '번역 누락',
    schemaErrors: '스키마 오류',
    placeholders: '프로필 미기입 항목',
    placeholdersEmpty: '모든 프로필 항목이 채워졌습니다',
    recent: '최근 수정',
    gitTitle: '커밋되지 않은 변경',
    gitClean: '커밋할 변경이 없습니다',
    gitCopy: '명령어 복사',
    gitCopied: '복사됨',
    selectAll: '전체 선택',
    selectedCount: (n: number, total: number) => `${n} / ${total}개 선택`,
    commitMessage: '커밋 메시지',
    commitMessagePlaceholder: '무엇을 바꿨는지 한 줄로',
    commit: '커밋',
    committing: '커밋 중…',
    committed: (hash: string, n: number) => `${hash} — 파일 ${n}개를 커밋했습니다`,
    push: '푸시',
    pushing: '푸시 중…',
    pushed: (n: number) => `커밋 ${n}개를 보냈습니다. GitHub Actions가 배포를 시작합니다`,
    pushNotice: '푸시하면 GitHub Actions가 빌드해 사이트에 반영합니다.',
    aheadCount: (n: number) => `푸시 대기 중인 커밋 ${n}개`,
    nothingToPush: '푸시할 커밋이 없습니다',
    behindWarning: (n: number) => `원격이 ${n}개 앞서 있습니다 — 먼저 git pull이 필요합니다`,
    noUpstream: '업스트림 브랜치가 없습니다',
    manualCommands: '터미널에서 직접 하기',
    pushConfirmTitle: '푸시하시겠습니까?',
    /** CRITICAL: 푸시 = 공개 배포. 되돌리기 어렵다는 사실을 확인 창에서 반드시 말한다. */
    pushWarning: '푸시는 곧 공개 배포입니다. 되돌리려면 새 커밋을 다시 푸시해야 합니다.',
    pushDraftWarning: (n: number) =>
      `초안 글이 ${n}편 있습니다. 사이트에는 안 보이지만 파일은 공개 리포지토리에 올라갑니다.`,
    emptyTitle: '아직 작성된 글이 없습니다',
    emptyHint: '첫 글을 만들면 여기에 통계가 쌓입니다.',
    firstPost: '첫 글 쓰기',
  },

  posts: {
    search: '제목·설명·태그 검색',
    allCategories: '전체 카테고리',
    allLanguages: '전체 언어',
    draftAll: '전체',
    draftOnly: '초안만',
    draftExclude: '공개만',
    newPost: '새 글',
    colStatus: '상태',
    colTitle: '제목',
    colCategory: '카테고리',
    colTags: '태그',
    colDate: '날짜',
    colTranslation: '번역',
    colActions: '동작',
    draftBadge: '초안',
    errorBadge: '오류',
    viewOnSite: '사이트에서 보기',
    delete: '삭제',
    addTranslation: '+ EN',
    addTranslationKo: '+ KO',
    emptyAll: '아직 작성된 글이 없습니다',
    emptyAllHint: '"새 글"을 눌러 첫 글을 만듭니다.',
    emptyFiltered: '조건에 맞는 글이 없습니다',
    emptyFilteredHint: '검색어나 필터를 바꿔 보세요.',
    deleteTitle: '이 글을 삭제할까요?',
    deleteWithTranslation: '번역본도 함께 삭제',
    deleteWarning: '커밋되지 않은 변경은 되돌릴 수 없습니다.',
    confirm: '삭제',
    cancel: '취소',
  },

  editor: {
    newTitle: '새 글',
    sectionBasic: '기본',
    sectionCover: '커버 이미지',
    sectionMeta: '카테고리 메타',
    fieldTitle: '제목',
    fieldDescription: '설명',
    fieldCategory: '카테고리',
    fieldSlug: '슬러그',
    fieldDate: '작성일',
    fieldUpdated: '수정일',
    fieldTags: '태그',
    fieldLang: '언어',
    fieldDraft: '초안',
    fieldMath: '수식(KaTeX)',
    fieldToc: '목차',
    fieldCover: '커버 이미지',
    fieldCoverAlt: '커버 설명(스크린리더용)',
    slugLocked: '슬러그 자동 생성이 잠겼습니다. 클릭해 해제하세요',
    slugManual: '영문 슬러그를 직접 입력해 주세요',
    slugDuplicate: '같은 카테고리에 같은 슬러그의 글이 이미 있습니다',
    langDerived: '파일 이름에서 파생됩니다',
    coverAltRequired: '커버를 지정했으면 설명이 필요합니다',
    body: '본문',
    /**
     * 마크다운의 소프트 줄바꿈 규칙은 처음 쓰는 사람이 반드시 걸리는 지점이다.
     * 프리뷰는 사이트와 똑같이 동작하므로, 규칙 자체를 여기서 알려 준다.
     */
    lineBreakHint:
      'Enter 한 번은 같은 문단으로 이어집니다 (마크다운 규칙). 문단을 나누려면 빈 줄을 하나 두고, 문단 안에서 줄만 바꾸려면 줄 끝에 역슬래시(\\)를 붙이세요.',
    preview: '프리뷰',
    edit: '편집',
    previewStale: '프리뷰를 갱신하지 못했습니다',
    previewJsx: 'MDX 컴포넌트 — 프리뷰에서 렌더링하지 않습니다',
    readingTime: (min: number) => `약 ${min}분`,
    insertLink: '링크 삽입',
    linkText: '보이는 글자',
    linkHref: '주소',
    linkHrefHint:
      '외부는 https://로 시작하고, 이 사이트 안이면 /paper-review/글슬러그 처럼 슬래시로 시작합니다. 앞에 슬래시가 없는 주소는 깨진 링크가 됩니다.',
    linkHrefRequired: '주소를 입력해야 링크를 넣을 수 있습니다.',
    insertImage: '이미지 삽입',
    pickImage: '올라간 이미지 중에서 고르기',
    imageAlt: '대체 텍스트 (스크린리더용)',
    imageWidth: '너비 (px, 선택)',
    imageWidthPlaceholder: '비우면 원본 크기',
    imageWidthHint:
      '본문에서 보이는 최대 너비입니다. 원본 파일은 그대로 두고 표시 크기만 줄입니다. 좁은 화면에서는 화면 폭에 맞춰 더 작아집니다.',
    imageAlign: '정렬',
    alignDefault: '기본 (글 흐름 그대로)',
    alignLeft: '왼쪽',
    alignCenter: '가운데',
    alignRight: '오른쪽',
    imageAlignHint: '이미지 상자의 위치만 옮깁니다. 글이 이미지를 감싸고 흐르지는 않습니다.',
    insert: '삽입',
    noImages: '아직 올린 이미지가 없습니다. 위 영역에 파일을 놓으면 바로 올라갑니다.',
    showSource: '원문 보기',
    sourceLabel: '반대 언어 원문',
    metaDiscardNotice: '이 값들은 저장 시 제거됩니다',
    categoryChangeWarning: '카테고리를 되돌리면 값이 살아납니다.',
    renameNotice: '번역본도 함께 이름이 바뀝니다',
    toolbar: {
      bold: '굵게',
      italic: '기울임',
      link: '링크',
      code: '코드',
      quote: '인용',
      math: '수식',
      image: '이미지 삽입',
      h2: 'H2',
      h3: 'H3',
    },
    staleTitle: '이 파일이 관리자 밖에서 변경되었습니다',
    staleLoadDisk: '디스크 내용 불러오기',
    staleOverwrite: '내 내용으로 덮어쓰기',
    staleCancel: '취소',
  },

  profile: {
    photo: '프로필 사진',
    photoReplace: '사진 교체',
    photoHint: '정사각형 640×640 이상 권장. 교체하면 기존 profile.* 파일이 삭제됩니다.',
    photoEmpty: '사진 없음 — 홈에는 이름 이니셜이 표시됩니다',
    basic: '기본',
    education: '학적',
    career: '경력',
    skills: '스킬',
    skillsIntro:
      '홈의 "스킬" 섹션입니다. 그룹은 칩 묶음 하나이며, 그룹명은 그 묶음의 왼쪽에 붙는 소제목입니다.',
    skillGroupNameHint:
      '예: Languages / ML·DL / Infra. 그룹을 하나만 쓴다면 비워 두세요 — 비우면 소제목 없이 칩만 나옵니다.',
    interests: '관심 분야',
    links: '링크',
    localized: '언어별',
    placeholder: '미기입',
    present: '진행 중',
    enrolledNow: '재학 중',
    workingNow: '재직 중',
    emptySection: '이 섹션은 사이트에서 통째로 사라집니다',
    interestLimit: '관심 분야는 최대 8개입니다',
    linkLimit: '링크는 최대 6개입니다',
    viewHome: '홈에서 확인',
    commentNotice:
      'PROFILE 선언 안의 줄 주석은 저장 시 사라집니다. 같은 설명이 파일 상단 인터페이스의 JSDoc에 남아 있습니다.',
  },

  settings: {
    site: '사이트',
    categories: '카테고리',
    analytics: '분석',
    readOnly: '읽기 전용',
    baseReason: '사용자 사이트에서는 항상 "/"입니다',
    navOrderReason: '카테고리 순서에서 자동으로 계산됩니다',
    urlEnvWarning: '환경변수 PUBLIC_SITE_URL이 이 값을 덮어씁니다',
    goatcounterSet: 'PUBLIC_GOATCOUNTER_CODE가 설정되어 있습니다',
    goatcounterUnset: 'PUBLIC_GOATCOUNTER_CODE가 설정되지 않았습니다 (분석 스크립트 미출력)',
    addCategory: '카테고리 추가',
    categoryInUse: (n: number) => `글 ${n}편이 이 카테고리를 사용 중입니다`,
    categoryIdLocked: 'id는 변경할 수 없습니다. 새 카테고리를 만들고 글을 옮기세요',
    restartNotice: '새 카테고리는 dev 서버 재시작 후 라우트에 반영됩니다',
    moveUp: '위로',
    moveDown: '아래로',
    remove: '삭제',
  },

  strings: {
    search: '경로·ko·en 전체 검색',
    untranslatedOnly: '미번역만',
    colPath: '경로',
    functionBadge: '코드에서만 수정',
    addKeyNotice: '새 키가 필요하면 src/config/i18n.ts를 직접 편집하세요.',
  },

  tags: {
    variants: (n: number) => `표기 ${n}종`,
    normalize: '정규화',
    rename: '이름 변경',
    merge: '병합',
    delete: '삭제',
    sortByCount: '사용 수',
    sortByName: '이름',
    usedIn: (n: number) => `글 ${n}편`,
    affected: (n: number) => `글 ${n}편의 tags가 다음과 같이 바뀝니다`,
    normalizeNotice: '프론트매터 형식이 관리자 규칙으로 정규화됩니다.',
    apply: '적용',
    empty: '아직 태그가 없습니다',
    emptyHint: '글 프론트매터의 tags 배열에 값을 넣으면 여기에 모입니다.',
    partial: (ok: number, failed: number) => `${ok}편 성공, ${failed}편 실패`,
  },

  assets: {
    dropHere: '여기에 이미지를 놓거나 클릭해 고르세요',
    dropMultiple: '여러 장을 한 번에 놓을 수 있습니다',
    copyPath: '경로 복사',
    copied: '복사됨',
    usage: '사용처 보기',
    delete: '삭제',
    inUse: (n: number) => `글 ${n}편에서 사용 중`,
    unused: '사용처 없음',
    empty: '아직 올린 이미지가 없습니다',
    emptyHint:
      '글에 넣을 이미지를 여기에 올려 두면 편집기의 커버·본문 삽입에서 바로 고를 수 있습니다.',
    tooLarge: (mb: number) => `파일이 ${mb}MB를 넘습니다`,
    uploading: '올리는 중…',
  },

  errors: {
    network: '개발 서버와 연결이 끊어졌습니다',
    sessionExpired: 'dev 서버가 재시작되었습니다. 새로고침하세요',
    notFound: '이 글은 더 이상 존재하지 않습니다(에디터에서 지웠을 수 있습니다)',
    unknown: '예상치 못한 오류입니다. 터미널 로그를 확인하세요',
  },
} as const;

export type AdminLabels = typeof L;
